<?php
// Compatibility URLs only. New pages and forms use the organized paths.
return [
    'index.html' => 'index.php',
    'action.php' => 'actions/handle.php',
    'login.php' => 'pages/auth/login.php',
    'login.html' => 'pages/auth/login.php',
    'signup.php' => 'pages/auth/signup.php',
    'signup.html' => 'pages/auth/signup.php',
    'forgot_password.php' => 'pages/auth/forgot-password.php',
    'forgot_password.html' => 'pages/auth/forgot-password.php',
    'reset_password.php' => 'pages/auth/reset-password.php',
    'reset_password.html' => 'pages/auth/reset-password.php',
    'Admin/Admin_dash.php' => 'pages/admin/dashboard.php',
    'Admin/Admin_dash.html' => 'pages/admin/dashboard.php',
    'Admin/report.php' => 'pages/admin/report.php',
    'Admin/report.html' => 'pages/admin/report.php',
    'Customer/Customer_dash.php' => 'pages/customer/dashboard.php',
    'Customer/Customer_dash.html' => 'pages/customer/dashboard.php',
    'Customer/Customer_Plant_store.php' => 'pages/customer/catalog.php',
    'Customer/Customer_Plant_store.html' => 'pages/customer/catalog.php',
    'Customer/Customer_Plant_details.php' => 'pages/customer/plant-details.php',
    'Customer/Customer_Plant_details.html' => 'pages/customer/plant-details.php',
    'Customer/Customer_Saved_Flora.php' => 'pages/customer/saved-plants.php',
    'Customer/Customer_Saved_Flora.html' => 'pages/customer/saved-plants.php',
    'Customer/Customer_myOrders.php' => 'pages/customer/orders.php',
    'Customer/Customer_myOrders.html' => 'pages/customer/orders.php',
    'Customer/Customer_gardenService.php' => 'pages/customer/book-service.php',
    'Customer/Customer_gardenService.html' => 'pages/customer/book-service.php',
    'Customer/Customer_live_chat.php' => 'pages/customer/chat.php',
    'Customer/Customer_live_chat.html' => 'pages/customer/chat.php',
    'Customer/checkout.php' => 'pages/customer/checkout.php',
    'Customer/checkout.html' => 'pages/customer/checkout.php',
    'Customer/order-confirmed.php' => 'pages/customer/order-confirmed.php',
    'Customer/order-confirmed.html' => 'pages/customer/order-confirmed.php',
    'Customer/customer-track-status.php' => 'pages/customer/track-order.php',
    'Customer/customer-track-status.html' => 'pages/customer/track-order.php',
    'Nursury_stuff/nursery_staff.php' => 'pages/staff/dashboard.php',
    'Nursury_stuff/nursery_staff.html' => 'pages/staff/dashboard.php',
    'Nursury_stuff/Nursery_live_chat.php' => 'pages/staff/chat.php',
    'Nursury_stuff/Nursery_live_chat.html' => 'pages/staff/chat.php',
    'Gardener/Gardener.php' => 'pages/gardener/dashboard.php',
    'Gardener/Gardener.html' => 'pages/gardener/dashboard.php',
    'Gardener/Gardener_live_chat.php' => 'pages/gardener/chat.php',
    'Gardener/Gardener_live_chat.html' => 'pages/gardener/chat.php',
    'payments/dummy.php' => 'pages/payments/dummy.php',
    'payments/dummy.html' => 'pages/payments/dummy.php',
];
